CC = gcc
CFLAGS = -Wall -Wextra -std=c99

all : exo1 exo2 exo3


exo1 : exo1.c
	$(CC) $(CFLAGS) -o exo1 exo1.c


exo2 : exo2.c
	$(CC) $(CFLAGS) -o exo2 exo2.c

exo3: exo3.c
	$(CC) $(CFLAGS) -o exo3 exo3.c
clean:
	rm -f exo1 exo2 exo3