CC = gcc
CFLAGS = -Wall -Wextra -std=c99

all: TP5Exo1 TP5Exo2 TP5Exo3

TP5Exo1: TP5Exo1.c
	$(CC) $(CFLAGS) -o TP5Exo1 TP5Exo1.c

TP5Exo2: TP5Exo2.c
	$(CC) $(CFLAGS) -o TP5Exo2 TP5Exo2.c

TP5Exo3: TP5Exo3.c
	$(CC) $(CFLAGS) -o TP5Exo3 TP5Exo3.c

clean:
	rm -f TP5exo1 TP5Exo2 TP5Exo3
